
= Coladay application
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:


[[overview]]
= Overview

The following section describes the key decisions and assumptions made to develop the application.

- A room can be booked for one hour.
- There are 20 rooms in total.
- The rooms are pretty similar in terms of size.
- In order to strike fairness in terms of reservation numbers, both companies will be a given a
configured quota number that default to 100 reservations.
- Both companies, to ease the reservations process, had put in charge user1 and user2 resp for
COKE and PEPSI . However the system is open to put more users.
- The available time slots to make a reservation are the following:

|===
|Timeslot

|8:00 am - 09:00 am

|09:00 am - 10:00 am

|10:00 am - 11:00 am

|11:00 am - 12:00 pm

|12:00 pm - 13:00 pm

|13:00 pm - 14:00 pm

|14:00 pm - 15:00 pm

|15:00 pm - 16:00 pm

|16:00 pm - 17:00 pm

|17:00 pm - 18:00 pm

|===



[[overview_http_verbs]]
== HTTP verbs

Coladay application tries to adhere as closely as possible to standard HTTP and REST conventions in
its use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `DELETE`
| Used to delete an existing resource
|===

[[overview_http_status_codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist

| `409 Not Found`
| The requested resource was in conflict with an existing one. The response body will include an
error providing further information.
|===

[[overview_hypermedia]]
== Hypermedia

Coladay uses hypermedia and resources include links to other resources in their
responses. Responses are in https://github.com/mikekelly/hal_specification[Hypertext
Application Language (HAL)] format. Links can be found beneath the `_links` key. Users of
the API should not create URIs themselves, instead they should use the above-described
links to navigate from resource to resource.

[[resources]]
= Resources

[[resources_reservation]]
== Reservation

The Reservation resources is used to create, delete, update and list resources.

[[resources_create_reservation]]
=== Creating a reservation

A `POST` request is used to create a reservation.

operation::create-a-reservation[snippets='curl-request,http-request,http-response']

[[resources_list_reservations]]
=== List reservations

A `GET` request is used to list all reservations.

operation::get-all-reservations-by-page[snippets='curl-request,http-request,http-response']

=== Cancel a reservation

A `DELETE` request is used to cancel a reservation.

operation::cancel-a-reservation[snippets='curl-request,http-request,http-response']

[[resources_room]]
== Room

[[resources_list_rooms]]
=== List rooms

A `GET` request is used to list all rooms and their availabilities.

operation::list-all-rooms[snippets='curl-request,http-request,http-response']


[[resources_user]]
== User

[[resources_list_users]]
=== List users

A `GET` request is used to list all users.

operation::list-all-users[snippets='curl-request,http-request,http-response']

[[resources_metrics]]
== Metrics

IMPORTANT: For testing purpose, the examples below use the default application port 8080 to access
the metric endpoints. However, in production the metric endpoints are accessible by default on port
8081.

=== List all metrics endpoints

A `GET` request is used to list all metrics endpoints.

operation::list-all-metrics-endpoints[snippets='curl-request,http-request,http-response']

=== List all application metrics

A `GET` request is used to list all application metrics.

operation::list-all-applications-metrics[snippets='curl-request,http-request,http-response']


=== Read application health

A `GET` request is used to read application health.

operation::read-application-health[snippets='curl-request,http-request,http-response']