version: '2'

volumes:
  grafana-storage: {}

services:
  app:
    image: 'selimyanat/coladay:latest'
    build:
      context: ../..
    container_name: coladay
    ports:
      - "9090:8080"
      - "9091:8081"
      - "9092:8000"
    depends_on:
      - db
    environment:
      - ENABLE_COLADAY_LOCAL_DEV=true
      - DB_ADMIN_URL=jdbc:postgresql://db:5432/postgres
      - DB_ADMIN_USER=postgres
      - DB_ADMIN_PASSWORD=secret
      - COLADAY_DB_NAME=coladay
      - COLADAY_DB_URL=jdbc:postgresql://db:5432/coladay
      - COLADAY_DB_USER=postgres
      - COLADAY_DB_USER_PASSWORD=secret
      - COLADAY_DB_SCHEMA=coladay
      - COLADAY_MIGRATION_DB_URL=jdbc:postgresql://db:5432/coladay?currentSchema=coladay
      - COLADAY_MIGRATION_DB_USER=postgres
      - COLADAY_MIGRATION_DB_USER_PASSWORD=secret

  db:
    image: 'postgres:11.4-alpine'
    container_name: db
    ports:
      - "9001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  prometheus:
    build: ./infrastructure/docker-compose/prometheus
    image: 'coladay/prom/prometheus:v2.31.1'
    container_name: prometheus
    restart: always
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "7070:9090"

  grafana:
    build: ./infrastructure/docker-compose/grafana
    image: 'coladay/grafana/grafana:8.2.3'
    container_name: grafana
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    depends_on:
      - prometheus
    user: '412'
