apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "coladay-chart.job.fullname" $ }}-initdb
  labels:
    name: {{ template "coladay-chart.fullname" . }}-initdb
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations}}
      {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end}}
      labels:
        name: {{ template "coladay-chart.fullname" . }}-initdb
    spec:
      restartPolicy: OnFailure
      containers:
          - name: {{ .Chart.Name }}-initdb-job
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: ENABLE_COLADAY_INIT_MODE
                value: "true"
              - name: ENABLE_COLADAY_LOCAL_DEV
                value: "false"
              - name: DB_ADMIN_URL
                value: {{ .Values.dbAdminUrl }}
              - name: DB_ADMIN_USER
                value: {{ .Values.dbAdminUser }}
              - name: DB_ADMIN_PASSWORD
                value: {{ .Values.dbAdminPassword }}
              - name: COLADAY_DB_NAME
                value: {{ .Values.coladayDbName }}
              - name: COLADAY_DB_URL
                value: {{ .Values.coladayDbUrl }}
              - name: COLADAY_DB_USER
                value: {{ .Values.coladayDbUser }}
              - name: COLADAY_DB_USER_PASSWORD
                value: {{ .Values.coladayDbPassword }}
              - name: COLADAY_DB_SCHEMA
                value: {{ .Values.coladayDbSchema }}
              - name: COLADAY_MIGRATION_DB_URL
                value: {{ .Values.coladayMigrationDbUrl }}
              - name: COLADAY_MIGRATION_DB_USER
                value: {{ .Values.coladayMigrationDbUser }}
              - name: COLADAY_MIGRATION_DB_USER_PASSWORD
                value: {{ .Values.coladayMigrationDbUserPassword }}
              - name: COLADAY_ROOT_PACKAGE_LOG_LEVEL
                value: {{ .Values.coladayLogLevel }}
            resources:
              {{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}

