  name: Feature Branch
  on:
    push:
      branches-ignore:
        - 'master'
        - 'release*'

  jobs:
    build:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
        - name: Build and Test
          run: ./mvnw --batch-mode --no-transfer-progress verify --update-snapshots verify

