  name: cola-day CI
  on: [push]

  jobs:
    build:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots verify

    artifact:
      name: Publish to Github package
      runs-on: ubuntu-20.04
      needs: [build]
      env:
        REPO: ${{ secrets.DOCKER_REPO }}
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
        - name: Publish artifact on GitHub Packages
          run: mvn -B clean deploy -DskipTests
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    docker:
      name: Publish to Docker hub
      runs-on: ubuntu-20.04
      needs: [build]
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
        - name: Build with Maven
          run: mvn clean install -DskipTests
        - name: Publish to Docker hub
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASS }}
            repository: selimyanat/coladay
            tags: ${{github.run_number}}
